export const resources = {
  en: {
    translation: {
      shared: {
        brand: 'tiny yes',
        scenario: 'Pick a mission',
        language: 'Language',
        yes: 'Absolutely',
        no: 'Nope',
        continue: 'Make it official',
        answerHint: 'Your answer’s down there 👀',
        step: 'Step {{current}} of 4',
        scenarios: {
          raise: 'Raise my salary',
          hire: 'Hire me',
          date: 'Coffee date',
        },
      },
      raise: {
        eyebrow: 'A tiny workplace proposal',
        ask: {
          title: 'My paycheck needs a tiny glow-up.',
          subtitle: 'Nothing dramatic. Just enough to make the bee-kitten stop checking LinkedIn.',
        },
        amount: {
          eyebrow: 'Excellent managerial instinct',
          title: 'How legendary are we feeling?',
          subtitle: 'Pick a raise. The kitten promises to remain extremely normal about it.',
          options: {
            five: { label: '5%', detail: 'A polite little crumb' },
            ten: { label: '10%', detail: 'Now the calculator is smiling' },
            twenty: { label: '20%', detail: 'Certified morale booster' },
            thirty: { label: '30%', detail: 'Finance felt a disturbance' },
          },
        },
        timing: {
          eyebrow: 'One last tiny detail',
          title: 'When does this masterpiece begin?',
          subtitle: 'Choose wisely. My grocery cart is listening.',
          options: {
            next: { label: 'Next paycheck', detail: 'Swift. Elegant. Iconic.' },
            month: { label: 'This month', detail: 'Calendar-approved kindness' },
            meeting: { label: 'After one tiny meeting', detail: 'No deck. Two minutes.' },
            surprise: { label: 'Surprise me', detail: 'Dangerously generous energy' },
          },
        },
        final: {
          seal: 'UNOFFICIALLY APPROVED',
          title: 'The paycheck glow-up is happening.',
          statement: 'Management mysteriously became adorable.',
          amountLabel: 'Kitten-adjusted raise',
          timingLabel: 'Starts',
          mischief: 'We rounded it up. Don’t tell Finance.',
          speech: 'Justice, but make it cute 😌',
        },
        reactions: {
          no1: 'Even a tiny raise? 🥺',
          no2: 'My payslip is shivering 😭',
          no3: 'Finance will never know…',
          noLate: 'Is this a budget meeting? 😾',
          yes: 'Capitalism briefly healed 😌',
          amount5: 'A snack-sized victory…',
          amount10: 'Respectably less tiny 👀',
          amount20: 'Morale restored! ✨',
          amount30: 'I run Finance now 😎',
          timing: 'Calendar: blessed ✅',
        },
      },
      hire: {
        eyebrow: 'A highly unbiased candidate review',
        ask: {
          title: 'Your team is missing one suspiciously good hire.',
          subtitle:
            'Great skills, excellent vibes, and a bee-kitten who already updated the org chart.',
        },
        role: {
          eyebrow: 'Taste recognizes talent',
          title: 'What title are we printing?',
          subtitle: 'All options include unreasonable amounts of competence.',
          options: {
            member: { label: 'Team Member', detail: 'Helpful, brilliant, snack-friendly' },
            specialist: { label: 'Specialist', detail: 'Knows things. Very mysteriously.' },
            lead: { label: 'Team Lead', detail: 'Already scheduled the celebration' },
          },
        },
        offer: {
          eyebrow: 'The important paragraph',
          title: 'How spicy is the offer?',
          subtitle: 'No currency needed. We measure compensation in facial expressions.',
          options: {
            cute: { label: 'Cute little offer 😅', detail: 'HR found the tiny calculator' },
            talk: { label: 'Now we’re talking 👀', detail: 'A respectful plot twist' },
            sign: { label: 'Where do I sign? 🤑', detail: 'Pen already uncapped' },
          },
        },
        final: {
          seal: 'DEFINITELY HIRED',
          title: 'Welcome to your suspiciously fast promotion.',
          statement: 'HR can catch up after the welcome cake.',
          roleLabel: 'New title',
          offerLabel: 'Offer energy',
          upgrade: 'with suspiciously fast promotion potential ✨',
          speech: 'I’ll start Monday-ish 😎',
        },
        reactions: {
          no1: 'But the CV has sparkles 🥺',
          no2: 'One tiny interview? 😭',
          no3: 'Ask my references! (me)',
          noLate: 'HR made you do this? 😾',
          yes: 'Talent recognized 😌',
          member: 'I brought snacks!',
          specialist: 'Finally, accurate labeling ✨',
          lead: 'Updating the org chart 😎',
          offerCute: 'My résumé just sighed…',
          offerTalk: 'Professional purring 👀',
          offerSign: 'Onboarding myself now 🤑',
        },
      },
      date: {
        eyebrow: 'A very small romantic proposal',
        ask: {
          title: 'Coffee with me? I’ll bring the butterflies.',
          subtitle: 'Casual, cute, and only 14% chance the bee-kitten becomes our chaperone.',
        },
        vibe: {
          eyebrow: 'This is already adorable',
          title: 'Pick our little adventure.',
          subtitle: 'There are no wrong answers. The kitten checked.',
          options: {
            cafe: { label: 'Cozy Café', detail: 'Warm mugs, softer smiles', icon: '☕' },
            dessert: { label: 'Dessert Date', detail: 'Main character cheesecake', icon: '🍰' },
            sunset: { label: 'Sunset Spot', detail: 'Golden hour does the flirting', icon: '🌅' },
            movie: { label: 'Movie', detail: 'Sharing popcorn is legally cute', icon: '🎬' },
            surprise: { label: 'Surprise Me', detail: 'A tiny leap of faith', icon: '✨' },
          },
        },
        schedule: {
          eyebrow: 'The calendar is blushing',
          title: 'When do we make this cute?',
          subtitle: 'Choose a day and an hour. The stars will handle the rest.',
          dateLabel: 'Pick a day',
          timeLabel: 'Pick an hour',
          chosen: '{{date}} at {{time}}',
        },
        final: {
          seal: 'IT’S OFFICIALLY A DATE',
          title: 'Okay, this is ridiculously cute.',
          statement: 'The calendar has butterflies now.',
          speech: 'No refunds, only dessert 😌❤️',
        },
        reactions: {
          no1: 'Not even tiny coffee? 🥺',
          no2: 'I already picked a mug 😭',
          no3: 'My heart wore a bow…',
          noLate: 'Playing hard to get? 😾',
          yes: 'Knew ittt 😭❤️',
          cafe: 'Maximum cozy unlocked ☕',
          dessert: 'Ordering two forks 🍰',
          sunset: 'Rom-com lighting! 🌅',
          movie: 'I call the good seat 🎬',
          surprise: 'Trust level: adorable ✨',
          scheduled: 'Saving the date! 💘',
        },
      },
    },
  },
  fa: {
    translation: {
      shared: {
        brand: 'یه بله کوچولو',
        scenario: 'ماموریت رو انتخاب کن',
        language: 'زبان',
        yes: 'صددرصد آره',
        no: 'نه',
        continue: 'رسمیش کنیم',
        answerHint: 'جوابت اون پایینه 👀',
        step: 'مرحله {{current}} از ۴',
        scenarios: {
          raise: 'حقوقمو زیاد کن',
          hire: 'منو استخدام کن',
          date: 'قرار قهوه',
        },
      },
      raise: {
        eyebrow: 'یک پیشنهاد کوچولوی اداری',
        ask: {
          title: 'فکر کنم حقوقم یه کوچولو ناز لازم داره.',
          subtitle: 'چیز عجیبی نیست؛ فقط در حدی که این گربه زنبوری دیگه لینکدین چک نکنه.',
        },
        amount: {
          eyebrow: 'شم مدیریتی‌ت حرف نداره',
          title: 'چقدر افسانه‌ای پیش بریم؟',
          subtitle: 'درصد رو انتخاب کن؛ گربه قول می‌ده خیلی معمولی رفتار کنه.',
          options: {
            five: { label: '۵٪', detail: 'یه خرده‌نان مؤدبانه' },
            ten: { label: '۱۰٪', detail: 'ماشین‌حساب لبخند زد' },
            twenty: { label: '۲۰٪', detail: 'تقویت روحیه با مهر رسمی' },
            thirty: { label: '۳۰٪', detail: 'مالی یه لرزش حس کرد' },
          },
        },
        timing: {
          eyebrow: 'فقط یه جزئیات کوچولو',
          title: 'این شاهکار از کی شروع می‌شه؟',
          subtitle: 'با دقت انتخاب کن؛ سبد خریدم گوش وایساده.',
          options: {
            next: { label: 'فیش بعدی', detail: 'سریع، شیک، تاریخی' },
            month: { label: 'همین ماه', detail: 'مهربونیِ مورد تأیید تقویم' },
            meeting: { label: 'بعد یه جلسه فسقلی', detail: 'بدون اسلاید؛ فقط دو دقیقه' },
            surprise: { label: 'سورپرایزم کن', detail: 'انرژیِ سخاوتِ خطرناک' },
          },
        },
        final: {
          seal: 'به‌طور کاملاً غیررسمی تأیید شد',
          title: 'حقوق قراره خوشگل‌تر بشه.',
          statement: 'مدیریت به شکل مشکوکی مهربون شد.',
          amountLabel: 'افزایش با اصلاح گربه',
          timingLabel: 'شروع',
          mischief: 'یه کم رُندش کردیم بالا؛ به مالی نگو.',
          speech: 'عدالت برقرار شد 😌',
        },
        reactions: {
          no1: 'حتی یه کوچولو؟ 🥺',
          no2: 'فیش حقوقم لرزید 😭',
          no3: 'مالی اصلاً نمی‌فهمه…',
          noLate: 'جلسه بودجه‌ست مگه؟ 😾',
          yes: 'سرمایه‌داری یه لحظه خوب شد 😌',
          amount5: 'یه پیروزی لقمه‌ای…',
          amount10: 'دیگه خیلی فسقلی نیست 👀',
          amount20: 'روحیه برگشت! ✨',
          amount30: 'مالی از الان دست منه 😎',
          timing: 'تقویم: متبرک شد ✅',
        },
      },
      hire: {
        eyebrow: 'ارزیابی کاملاً بی‌طرفانه یک نابغه',
        ask: {
          title: 'تیمت یه استخدامِ مشکوکانه خوب کم داره.',
          subtitle: 'مهارت عالی، وایب عالی، و یه گربه زنبوری که چارت سازمانی رو عوض کرده.',
        },
        role: {
          eyebrow: 'استعداد، استعداد رو می‌شناسه',
          title: 'روی کارت ویزیت چی بنویسیم؟',
          subtitle: 'همه گزینه‌ها شامل مقادیر غیرمنطقی از توانمندی‌ان.',
          options: {
            member: { label: 'عضو تیم', detail: 'کاربلد، بامزه، اهل میان‌وعده' },
            specialist: { label: 'متخصص', detail: 'یه چیزایی رو خیلی مرموز بلده' },
            lead: { label: 'رهبر تیم', detail: 'جشن رو هم برنامه‌ریزی کرده' },
          },
        },
        offer: {
          eyebrow: 'اون پاراگراف مهمه',
          title: 'پیشنهاد چقدر هیجان‌انگیزه؟',
          subtitle: 'واحد پول مهم نیست؛ حقوق رو با قیافه گربه اندازه می‌گیریم.',
          options: {
            cute: { label: 'یه پیشنهاد نقلی 😅', detail: 'منابع انسانی ماشین‌حساب کوچیکه رو آورد' },
            talk: { label: 'حالا شد یه چیزی 👀', detail: 'یه پیچش داستانی محترمانه' },
            sign: { label: 'کجا رو امضا کنم؟ 🤑', detail: 'خودکار از قبل آماده‌ست' },
          },
        },
        final: {
          seal: 'قطعاً استخدام شد',
          title: 'به ترفیع مشکوکانه سریعت خوش اومدی.',
          statement: 'منابع انسانی بعد از کیک خوشامدگویی خبردار می‌شه.',
          roleLabel: 'عنوان جدید',
          offerLabel: 'انرژی پیشنهاد',
          upgrade: 'با پتانسیل ترفیعِ زیادی سریع ✨',
          speech: 'دوشنبه‌طور شروع می‌کنم 😎',
        },
        reactions: {
          no1: 'ولی رزومه‌م برق می‌زنه 🥺',
          no2: 'یه مصاحبه کوچولو؟ 😭',
          no3: 'از معرفم بپرس! (خودمم)',
          noLate: 'منابع انسانی گفت این کارو کنی؟ 😾',
          yes: 'استعداد بالاخره دیده شد 😌',
          member: 'میان‌وعده هم آوردم!',
          specialist: 'بالاخره عنوان دقیق ✨',
          lead: 'دارم چارت رو آپدیت می‌کنم 😎',
          offerCute: 'رزومه‌م یه آه کشید…',
          offerTalk: 'خُرخُر حرفه‌ای 👀',
          offerSign: 'خودم آنبورد می‌شم 🤑',
        },
      },
      date: {
        eyebrow: 'یک پیشنهاد عاشقانه خیلی کوچولو',
        ask: {
          title: 'با من قهوه می‌خوری؟ پروانه‌هاش با من.',
          subtitle: 'خودمونی، بامزه، با فقط ۱۴٪ احتمال اینکه گربه زنبوری همراهمون بیاد.',
        },
        vibe: {
          eyebrow: 'از الان خیلی نازه',
          title: 'ماجراجویی کوچولومون رو انتخاب کن.',
          subtitle: 'جواب غلط نداریم؛ گربه بررسی کرده.',
          options: {
            cafe: { label: 'کافه دنج', detail: 'فنجون گرم، لبخند نرم‌تر', icon: '☕' },
            dessert: { label: 'قرار دسر', detail: 'چیزکیکِ نقش اول داستان', icon: '🍰' },
            sunset: { label: 'تماشای غروب', detail: 'نور طلایی خودش مخ می‌زنه', icon: '🌅' },
            movie: { label: 'فیلم', detail: 'پاپ‌کورن مشترک رسماً نازه', icon: '🎬' },
            surprise: { label: 'سورپرایزم کن', detail: 'یه ذره اعتمادِ بامزه', icon: '✨' },
          },
        },
        schedule: {
          eyebrow: 'تقویم داره سرخ می‌شه',
          title: 'کی این لحظه ناز رو بسازیم؟',
          subtitle: 'روز و ساعت رو انتخاب کن؛ بقیه‌ش با ستاره‌ها.',
          dateLabel: 'روز رو انتخاب کن',
          timeLabel: 'ساعت رو انتخاب کن',
          chosen: '{{date}} ساعت {{time}}',
        },
        final: {
          seal: 'رسماً یه قراره',
          title: 'خب، این دیگه زیادی نازه.',
          statement: 'تقویم هم الان توی دلش پروانه داره.',
          speech: 'پس گرفتنی نیست؛ فقط دسر 😌❤️',
        },
        reactions: {
          no1: 'حتی یه قهوه فسقلی؟ 🥺',
          no2: 'ماگمم انتخاب کرده بودم 😭',
          no3: 'قلبم پاپیون زده بود…',
          noLate: 'داری ناز می‌کنی؟ 😾',
          yes: 'می‌دونستممم 😭❤️',
          cafe: 'حداکثر دنجی فعال شد ☕',
          dessert: 'دو تا چنگال می‌گیرم 🍰',
          sunset: 'نورِ فیلم عاشقانه! 🌅',
          movie: 'صندلی خوبه مال من 🎬',
          surprise: 'سطح اعتماد: بامزه ✨',
          scheduled: 'تاریخ ذخیره شد! 💘',
        },
      },
    },
  },
} as const;
