export const resources = {
  en: {
    translation: {
      shared: {
        scenario: 'Pick your mission',
        language: 'Language',
        kitten: 'Kitten',
        mascotLabel: 'Orange kitten mascot',
        decorations: {
          paycheck: 'PAY',
          resume: 'CV',
          hired: 'HIRED',
        },
        yes: 'Yes, deal 😌',
        no: 'Not yet',
        continue: 'That’s the one',
        step: 'Step {{current}} of 4',
        scenarios: {
          raise: 'Get a raise',
          hire: 'Hire me',
          date: 'Plan a date',
        },
      },

      memory: {
        switching: {
          reaction: 'Three plans in eight seconds. Ambitious.',
        },
        effects: {
          raiseSmall: 'Petty cash',
          raiseBig: 'Payday energy',
          raisePersistence: 'Still negotiating',
          hireLead: 'Boss mode',
          hireSigned: 'Signed',
          hirePersistence: 'Still interviewing',
          dateDessert: 'Dessert secured',
          dateSunset: 'Golden hour',
          dateSurprise: 'No spoilers',
          dateNight: 'Night plan',
          dateEarly: 'Early bird',
          datePersistence: 'Still asking',
          switching: 'Pick a lane',
        },
      },

      raise: {
        eyebrow: 'Quick question, boss',
        ask: {
          title: 'Can we make my next paycheck a little better?',
          subtitle:
            'Nothing dramatic. Just enough to look at grocery prices without taking it personally.',
        },
        amount: {
          eyebrow: 'Let’s talk numbers',
          title: 'How good is this news?',
          subtitle: 'Choose freely. I have prepared several facial expressions.',
          options: {
            five: { label: '5%', detail: 'A cautious beginning' },
            ten: { label: '10%', detail: 'Now we’re talking' },
            twenty: { label: '20%', detail: 'That would actually help' },
            thirty: { label: '30%', detail: 'Now that’s a number' },
          },
        },
        timing: {
          eyebrow: 'One last detail',
          title: 'When does this become official?',
          subtitle: 'Two real answers. Two answers that may try to escape.',
          options: {
            next: { label: 'Today', detail: 'My favorite kind of scheduling' },
            month: { label: 'Next week', detail: 'Fine. I have a good memory.' },
          },
          decoys: {
            approval: 'After management approval',
            whenever: 'Whenever it happens',
          },
        },
        final: {
          seal: 'PAYROLL HAS BEEN INFORMED',
          title: 'Approved. I have witnesses.',
          statement:
            'Case closed. I’m off to spend it so we can run this whole plan again next month. 💸',
          selectedLabel: 'You picked',
          adjustmentLabel: 'Kitten bonus',
          amountLabel: 'Approved raise',
          timingLabel: 'Effective',
          mischief: '+2% added by me for being charming. 😌',
          speech: 'Right. My work here is done. 😌',
          punchline:
            'Case closed. I’m off to spend it so we can run this whole plan again next month. 💸',
        },
        recipient: {
          label: 'Boss',
          no1: 'Finance said not right now.',
          no2: 'The budget is tight.',
          no3: 'Let’s talk next month.',
          no4: 'We need another meeting.',
          no5: 'Let’s talk after performance reviews.',
          noLate: 'Let me see what happens.',
        },
        reactions: {
          no1: 'Finance talks a lot.',
          no2: 'Then find me a little room somewhere. 🥺',
          no3: 'You said “next month” last time too.',
          no4: 'Is that the meeting before the next meeting?',
          no5: 'I reviewed mine. Great score.',
          noLate: 'I’ll be right here.',
          noPool1: 'Wait… seriously?',
          noPool2: 'Fine for now. I will remember this.',
          noPool3: 'No again? Are you practicing?',
          noPool4: 'Look at me, being patient.',
          noPool5: 'That’s three. I’m counting.',
          noPool6: 'Four. We may have a pattern.',
          noPool7: 'Five? I respect the commitment.',
          noPool8: 'This is getting funny now.',
          noPool9: 'Still here, for the record.',
          yes: 'Knew logic would win eventually.',
          amount5: 'Oh, that was the warm-up.',
          amount10: 'Ten percent? We’re starting to understand each other.',
          amount20: 'Right. Now we’re getting somewhere sensible.',
          amount30: 'Why weren’t you this reasonable from the start? 😌',
          today: 'Today? I love that answer.',
          nextWeek: 'Deal. Just know I have a very good memory.',
        },
        memory: {
          eggs: {
            no6a: 'Six times? Loved the persistence. Not the choice.',
            no6b: 'Six times? Are you going for a record?',
            no10: 'Ten times? Are you going for a record?',
            persistenceThirty: 'After all those no’s, thirty percent surprised me too.',
          },
        },
      },

      hire: {
        eyebrow: 'A very short application',
        ask: {
          title: 'Should I just join your team?',
          subtitle: 'We can skip the mysterious “we’ll be in touch” part.',
        },
        role: {
          eyebrow: 'Let’s print the badge',
          title: 'What goes under my name?',
          subtitle: 'Pick carefully. I will update my bio immediately.',
          options: {
            member: {
              label: 'Team Member',
              detail: 'Reliable. Knows where the snacks are.',
            },
            specialist: {
              label: 'Specialist',
              detail: 'Gets called when it gets weird',
            },
            lead: { label: 'Team Lead', detail: 'Owns a notebook and opinions' },
          },
        },
        offer: {
          eyebrow: 'Now the salary tier',
          title: 'What salary tier are we talking?',
          subtitle: 'No exact numbers. We’re keeping this cordial.',
          options: {
            cute: { label: 'Low', detail: 'A very cautious opening' },
            talk: { label: 'Medium', detail: 'A respectable middle ground' },
            sign: { label: 'High', detail: 'Now we have an offer' },
          },
        },
        final: {
          seal: 'ACCESS GRANTED',
          title: 'Hired. Excellent decision.',
          statement: 'Hiring file: closed.',
          passLabel: 'NEW TEAM MEMBER',
          roleLabel: 'Position',
          offerLabel: 'Salary tier',
          upgrade: 'Cleared for the first day',
          speech: 'I got in? Wow. Completely unexpected.',
          speech2: 'Good. Now the real question: how’s lunch around here?',
          punchline1: 'Hiring file: closed.',
          punchline2: 'Case closed. I’m off to update LinkedIn. 😌',
          punchline3: 'Hired. Now I can complain about meetings with a clear conscience.',
        },
        recipient: {
          label: 'Recruiter',
          no1: 'We don’t have an open role right now.',
          no2: 'We don’t have an open role right now.',
          no3: 'We’ll get back to you later.',
          no4: 'There’s one more interview stage.',
          no5: 'We need to check with the team manager.',
          no6: 'The manager needs to approve it.',
          no7: 'We need a reference.',
          no8: 'The role isn’t final yet.',
          no9: 'The team hasn’t decided yet.',
          no10: 'We need to see what the projects need.',
          no11: 'You’ll need to wait a little.',
        },
        reactions: {
          no1: 'I barely take up any space.',
          no2: 'Then add one chair.',
          no3: 'When exactly is “later”? Asking for a friend.',
          no4: 'Are you hiring me or renewing the show for another season?',
          no5: 'Give me their number. We can start the teamwork now.',
          no6: 'Once the manager sees me, this gets easier. 😌',
          no7: 'I highly recommend myself. Does that count?',
          no8: 'Finalize it. I’m ready.',
          no9: 'Want me to summarize? Me.',
          no10: 'Me. The projects just don’t know it yet.',
          no11: 'Fine. Does the waiting count as work experience?',
          noPool1: 'Wait… you did read my résumé, right?',
          noPool2: 'Okay. Think one more time.',
          noPool3: 'No again? Is this an interview stage?',
          noPool4: 'Right, so we’re still negotiating.',
          noPool5: 'That’s three. I’m putting this down as experience.',
          noPool6: 'Look at me, still being professional.',
          noPool7: 'Four times? HR is thorough today.',
          noPool8: 'Five no’s and the interview continues. Curious.',
          noPool9: 'Still ready to start Saturday, just so you know.',
          noPool10: 'This hiring process is getting a little long, no?',
          yes1: 'Knew it. I was just waiting for you to make it official.',
          yes2: 'That’s better. Where do I sign?',
          member1: 'Fine. We’ll start quietly.',
          member2: 'Team Member? I’ll accept it for now.',
          member3: 'Good start. I’ll handle the rest.',
          specialist: 'Specialist? Suits me, doesn’t it?',
          lead: 'Finally, the org chart makes sense.',
          offerLow: 'Fine… I just won’t tell anyone about it yet.',
          offerMedium: 'Right. We’re getting close to an agreement.',
          offerHigh: 'Knew that if I was reasonable, you’d be reasonable too.',
        },
        memory: {
          eggs: {
            no6a: 'Six times? This interview has been very thorough.',
            no6b: 'Six rejections and I’m still polite. That’s a skill.',
            no10a: 'Ten times? Am I the candidate or a longtime employee?',
            no10b: 'That’s ten. Should I put this process on my résumé?',
            leadHigh: 'Right. Now it’s time for me to hire someone.',
            leadLow: 'Team Lead with this offer? I admire the confidence.',
            persistenceYes: 'Finally! I was getting ready for the next stage.',
            persistenceHigh: 'This offer after all those no’s? No complaints here.',
          },
        },
      },

      date: {
        eyebrow: 'A low-pressure question',
        ask: {
          title: 'Want to get coffee with me?',
          subtitle: 'One coffee. If it’s awkward, we can blame the chairs.',
        },
        vibe: {
          eyebrow: 'Okay, we have a plan',
          title: 'What sounds good?',
          subtitle: 'I’ll handle the nerves. You pick the place.',
          options: {
            cafe: {
              label: 'Coffee somewhere cozy',
              detail: 'Easy start. Good lighting.',
              icon: '☕',
            },
            dessert: {
              label: 'Dessert first',
              detail: 'Responsible choices can wait.',
              icon: '🍰',
            },
            sunset: {
              label: 'Catch the sunset',
              detail: 'A walk and something nice to look at',
              icon: '🌅',
            },
            movie: {
              label: 'Movie night',
              detail: 'Shared popcorn. Terms negotiable.',
              icon: '🎬',
            },
            surprise: {
              label: 'Choose for me',
              detail: 'I’ll show up with no complaints.',
              icon: '✨',
            },
          },
        },
        schedule: {
          eyebrow: 'Put it in the calendar',
          title: 'When are you free?',
          subtitle: 'Pick a time. I need a fair chance to decide what to wear.',
          dateLabel: 'Pick a day',
          timeLabel: 'Pick a time',
          chosen: '{{date}} at {{time}}',
        },
        final: {
          seal: 'IT’S A DATE',
          title: 'See you there.',
          statement: 'Date booked. Cancelling carries a dessert penalty.',
          activityLabel: 'The plan',
          dateLabel: 'Day',
          timeLabel: 'Time',
          ticketNote: 'Keep this. It settles any future “what time was it?” debate.',
          speech: 'Official. Now I can be excited in peace.',
          speech2: 'Good. That part went exactly according to plan.',
          punchline1: 'Date booked. Cancelling carries a dessert penalty.',
          punchline2: 'Case closed. I’m off to figure out what to wear.',
          punchline3: 'Date confirmed. I’ve already arrived five minutes early.',
        },
        recipient: {
          label: 'Them',
          no1: 'This week is packed.',
          no2: 'I don’t drink coffee.',
          no3: 'Let me think about it.',
          no4: 'Maybe next week.',
          no5: 'I don’t know where we should go.',
          no6: 'I don’t know where we should go.',
          no7: 'I might be a little late.',
          no8: 'I’m still not sure.',
          no9: 'I’ve been a little tired lately.',
          no10: 'I prefer staying home at night.',
          no11: 'This is a little sudden.',
        },
        reactions: {
          no1: 'I’m small. I’ll fit. 🥺',
          no2: 'Then falafel is officially approved. 😌',
          no3: 'Think. I’ll pretend I’m not nervous for now.',
          no4: 'Fine. My plan next week is still you.',
          no5: 'You just show up. I’ll know a place by then.',
          no6: 'Leave that part to me.',
          no7: 'I’ve already forgiven the first five minutes. 😌',
          no8: 'I’m sure enough for both of us. 😌',
          no9: 'Then a quiet date. I promise not to get too excited… not a firm promise.',
          no10: 'Then earlier. Look how reasonably I negotiate.',
          no11: 'Maybe for you. I’ve had a plan for a while. 😌',
          noPool1: 'Wait… that answer wasn’t in my plan.',
          noPool2: 'Fine. Play a little hard to get.',
          noPool3: 'Okay… I’m not upset yet. Yet.',
          noPool4: 'No again? Are you testing me?',
          noPool5: 'Fine. I still have my dignity.',
          yes: 'Right. Now I have to pretend I’m very calm.',
          cafe: 'Coffee? Safe, cozy, and a very good start.',
          dessert: 'You picked dessert? Your taste is officially approved.',
          sunset: 'Sunset works. Almost too well, actually.',
          movie: 'A movie? Good. We can fake-argue about it afterward.',
          surprise1: 'A surprise? Fine. My reputation is involved now.',
          surprise2: 'All right. You asked for it—don’t complain later that it was too good.',
          scheduled: 'Got it. I’m setting three reminders.',
          timeEarly: 'Early morning? I don’t have a personality at that hour.',
          timeNoon: 'I’m just as charming at noon as I am any other time. 😌',
          timeAfternoon: 'I’m just as charming in the afternoon as I am any other time. 😌',
          timeNight: 'I like night. It’s romantic. 😌',
          timeMidnight: 'Midnight? You’re clearly not into ordinary decisions.',
        },
        memory: {
          eggs: {
            no6a: 'Six times? I’m starting to like the determination a little.',
            no6b: 'That’s six. All this effort to say no is attention of some kind. 😌',
            no10a: 'Ten times? Statistically, this is getting serious.',
            no10b: 'That’s ten. At this point I’m only staying out of curiosity.',
            persistenceYes1: 'Finally! Wait, I wasn’t ready for this moment.',
            persistenceYes2: 'See? Reasonable people find each other eventually. 😌',
            surpriseMidnight1: 'Midnight and a surprise? I respect the confidence.',
            surpriseMidnight2: 'You chose this combination. I have witnesses.',
            manyActivities1: 'Are you choosing a date or testing me?',
            manyActivities2: 'Fourth choice… and somehow I’m fine with all of them.',
          },
        },
      },
    },
  },

  fa: {
    translation: {
      shared: {
        scenario: 'امروز کدوم مأموریت؟',
        language: 'زبان',
        kitten: 'گربه',
        mascotLabel: 'گربه نارنجی',
        decorations: {
          paycheck: 'فیش',
          resume: 'رزومه',
          hired: 'استخدام',
        },
        yes: 'آره، قبوله 😌',
        no: 'فعلاً نه',
        continue: 'همینه، قطعی‌ش کن',
        step: 'مرحله {{current}} از ۴',
        scenarios: {
          raise: 'افزایش حقوق',
          hire: 'استخدامم کن',
          date: 'قرار دونفره',
        },
      },

      memory: {
        switching: {
          reaction: 'سه تا برنامه تو هشت ثانیه؟ بلندپروازانه‌ست.',
        },
        effects: {
          raiseSmall: 'پول خرد',
          raiseBig: 'حال‌وهوای روز حقوق',
          raisePersistence: 'مذاکره ادامه دارد',
          hireLead: 'حالت مدیریت',
          hireSigned: 'امضا شد',
          hirePersistence: 'مصاحبه ادامه دارد',
          dateDessert: 'دسر قطعی شد',
          dateSunset: 'وقت غروب',
          dateSurprise: 'بدون اسپویل',
          dateNight: 'قرار شبانه',
          dateEarly: 'سحرخیز',
          datePersistence: 'هنوز دارم می‌پرسم',
          switching: 'بالاخره کدوم؟',
        },
      },

      raise: {
        eyebrow: 'رئیس، یه دقیقه کار دارم',
        ask: {
          title: 'می‌شه فیش بعدیم یه کم بهتر باشه؟',
          subtitle:
            'چیز عجیبی نمی‌خوام؛ فقط آخر ماه، قبل از هر خرید، لازم نباشه با خودم جلسه بذارم.',
        },
        amount: {
          eyebrow: 'بریم سراغ عددها',
          title: 'این خبر خوب، چقدر خوبه؟',
          subtitle: 'راحت انتخاب کن؛ من برای هر گزینه یه قیافه آماده دارم.',
          options: {
            five: { label: '۵٪', detail: 'شروع محتاطانه' },
            ten: { label: '۱۰٪', detail: 'خب، شد یه چیزی' },
            twenty: { label: '۲۰٪', detail: 'این یکی آبرومنده' },
            thirty: { label: '۳۰٪', detail: 'می‌دونستم دستت بازه' },
          },
        },
        timing: {
          eyebrow: 'فقط تاریخ اجرا',
          title: 'از کِی رسمی‌ش کنیم؟',
          subtitle: 'دو تا جواب واقعی داریم، دو تا جواب هم ممکنه فرار کنن.',
          options: {
            next: { label: 'امروز', detail: 'جواب موردعلاقه‌م' },
            month: { label: 'هفته بعد', detail: 'قبوله؛ یادم می‌مونه' },
          },
          decoys: {
            approval: 'بعد از تأیید مدیریت',
            whenever: 'هر وقت شد',
          },
        },
        final: {
          seal: 'مالی در جریان قرار گرفت',
          title: 'تصویب شد؛ شاهد هم دارم',
          statement:
            'پرونده بسته شد. برم پولامو خرج کنم که ماه بعد دوباره همین برنامه رو با هم پیاده کنیم 💸',
          selectedLabel: 'انتخاب شما',
          adjustmentLabel: 'جایزه گربه',
          amountLabel: 'افزایش تصویب‌شده',
          timingLabel: 'زمان اجرا',
          mischief: '+۲٪ هم خودم به خاطر جذابیتم اضافه کردم 😌',
          speech: 'خب، کار من اینجا تمومه 😌',
          punchline:
            'پرونده بسته شد. برم پولامو خرج کنم که ماه بعد دوباره همین برنامه رو با هم پیاده کنیم 💸',
        },
        recipient: {
          label: 'مدیر',
          no1: 'مالی گفته فعلاً نه.',
          no2: 'بودجه کمه.',
          no3: 'بذار ماه دیگه صحبت کنیم.',
          no4: 'باید یه جلسه دیگه بذاریم.',
          no5: 'بعد از ارزیابی عملکرد صحبت می‌کنیم.',
          noLate: 'بذار ببینم چی می‌شه.',
        },
        reactions: {
          no1: 'مالی خیلی حرف می‌زنه.',
          no2: 'خب یه کوچولو از یه جاش پیدا کنین دیگه 🥺',
          no3: 'همین «ماه دیگه» رو دفعه قبل هم گفتی.',
          no4: 'جلسه بعدی هم قراره جلسه قبل از جلسه بعدی باشه؟',
          no5: 'ارزیابیمو خودم انجام دادم، نمره خوبی گرفتم.',
          noLate: 'من همین‌جا وایسادم.',
          noPool1: 'عه… جدی؟',
          noPool2: 'باشه حالا... ولی یادم می‌مونه.',
          noPool3: 'بازم نه؟ داری تمرین می‌کنی؟',
          noPool4: 'منو باش که دارم صبر می‌کنم.',
          noPool5: 'سومین باره‌ها، دارم می‌شمرم.',
          noPool6: 'چهار تا شد... داریم یه الگو می‌بینیم.',
          noPool7: 'پنج تا؟ باشه، پشتکارت قابل احترامه.',
          noPool8: 'دیگه داره بامزه می‌شه.',
          noPool9: 'من هنوز اینجام، جهت اطلاع.',
          yes: 'می‌دونستم منطق بالاخره برنده می‌شه.',
          amount5: 'عه، این که گرم کردن بود.',
          amount10: 'ده درصد؟ خب، کم‌کم داریم همدیگه رو می‌فهمیم.',
          amount20: 'خب، داریم به یه جای درست می‌رسیم.',
          amount30: 'خب چرا از اول همین‌قدر منطقی نبودی؟ 😌',
          today: 'امروز؟ عاشق این جوابم.',
          nextWeek: 'قبوله، ولی من حافظه‌م خوبه‌ها.',
        },
        memory: {
          eggs: {
            no6a: 'شیش بار؟ پشتکارتو دوست داشتم، انتخابتو نه.',
            no6b: 'شیش بار؟ داری رکورد می‌زنی؟',
            no10: 'ده بار؟ داری رکورد می‌زنی؟',
            persistenceThirty: 'بعد این همه نه، سی درصد؟ منم یه لحظه جا خوردم.',
          },
        },
      },

      hire: {
        eyebrow: 'یه درخواست کاری کوتاه',
        ask: {
          title: 'چطوره منو بیارین تو تیمتون؟',
          subtitle: 'اون بخشِ «خبرتون می‌کنیم» رو هم می‌تونیم رد کنیم.',
        },
        role: {
          eyebrow: 'بریم کارت پرسنلی رو چاپ کنیم',
          title: 'زیر اسمم چی بنویسیم؟',
          subtitle: 'دقیق انتخاب کنین؛ من همون لحظه عنوان شغلیم رو عوض می‌کنم.',
          options: {
            member: {
              label: 'عضو تیم',
              detail: 'قابل اعتماد؛ جای خوراکی‌ها رو هم بلده',
            },
            specialist: {
              label: 'متخصص',
              detail: 'وقتی کار گره می‌خوره صدام می‌کنن',
            },
            lead: { label: 'رهبر تیم', detail: 'دفترچه داره، نظر هم زیاد داره' },
          },
        },
        offer: {
          eyebrow: 'حالا رده حقوق',
          title: 'حقوقمون تو چه رده‌ای باشه؟',
          subtitle: 'عدد دقیق نمی‌پرسیم؛ فعلاً همون رده کافیه.',
          options: {
            cute: { label: 'کم', detail: 'شروع خیلی محتاطانه' },
            talk: { label: 'متوسط', detail: 'یه پیشنهاد قابل قبول' },
            sign: { label: 'زیاد', detail: 'خب، این شد حرف حساب' },
          },
        },
        final: {
          seal: 'دسترسی صادر شد',
          title: 'استخدام شدم؛ تصمیم خوبیه',
          statement: 'پرونده استخدام: بسته شد.',
          passLabel: 'عضو جدید تیم',
          roleLabel: 'سمت',
          offerLabel: 'رده حقوق',
          upgrade: 'آماده برای اولین روز کاری',
          speech: 'قبول شدم؟ عه، چه اتفاق غیرمنتظره‌ای.',
          speech2: 'خب، حالا بریم سر اصل مطلب: ناهار شرکت چطوره؟',
          punchline1: 'پرونده استخدام: بسته شد.',
          punchline2: 'پرونده بسته شد. برم LinkedIn رو آپدیت کنم 😌',
          punchline3: 'استخدام شدم. حالا می‌تونم با خیال راحت از جلسه‌ها شکایت کنم.',
        },
        recipient: {
          label: 'کارشناس جذب',
          no1: 'فعلاً پوزیشن باز نداریم.',
          no2: 'فعلاً پوزیشن باز نداریم.',
          no3: 'بعداً خبرتون می‌کنیم.',
          no4: 'یه مرحله دیگه مصاحبه مونده.',
          no5: 'باید با مدیر تیم هماهنگ کنیم.',
          no6: 'مدیر باید تأیید کنه.',
          no7: 'نیاز به معرف داریم.',
          no8: 'پوزیشن هنوز نهایی نشده.',
          no9: 'تیم هنوز جمع‌بندی نکرده.',
          no10: 'باید ببینیم پروژه‌ها به کی نیاز دارن.',
          no11: 'باید یکم صبر کنی.',
        },
        reactions: {
          no1: 'من خیلی جا نمی‌گیرم.',
          no2: 'خب یه صندلی اضافه کنین دیگه.',
          no3: 'خب «بعداً» دقیقاً کِی می‌شه؟ برای دوستم می‌پرسم.',
          no4: 'دارین استخدامم می‌کنین یا فصل جدید سریاله؟',
          no5: 'شماره‌شو بده، کار تیمی رو از همین الان شروع کنیم.',
          no6: 'مدیر که منو ببینه، کارمون راحت‌تر می‌شه 😌',
          no7: 'خودم از خودم خیلی راضیم، قبول نیست؟',
          no8: 'نهاییش کنین، من که آماده‌م.',
          no9: 'جمع‌بندیشونو من بگم؟ من.',
          no10: 'به من. فقط هنوز خودشون خبر ندارن.',
          no11: 'باشه. ولی این صبر جزو سابقه کارم حساب می‌شه؟',
          noPool1: 'عه… رزومه‌مو دیدی دیگه؟',
          noPool2: 'باشه، یه بار دیگه فکر کن.',
          noPool3: 'بازم نه؟ این جزو مراحل مصاحبه‌ست؟',
          noPool4: 'خب، پس هنوز داریم مذاکره می‌کنیم.',
          noPool5: 'سه تا شد. من اینو سابقه کار رد می‌کنم.',
          noPool6: 'منو باش که هنوز حرفه‌ای رفتار می‌کنم.',
          noPool7: 'چهار بار؟ HR خیلی دقیق شده امروز.',
          noPool8: 'پنج تا نه و هنوز مصاحبه ادامه داره. عجیبه.',
          noPool9: 'من هنوز برای شروع شنبه آماده‌م، جهت اطلاع.',
          noPool10: 'این پروسه استخدام یه کم طولانی شد، نه؟',
          yes1: 'می‌دونستم. فقط منتظر بودم رسمی‌ش کنی.',
          yes2: 'حالا شد. کجا باید امضا کنم؟',
          member1: 'باشه، آروم شروع می‌کنیم.',
          member2: 'Team Member؟ فعلاً قبول.',
          member3: 'شروع خوبیه. ادامه‌ش با خودم.',
          specialist: 'Specialist؟ بهم میاد، نه؟',
          lead: 'بالاخره چارت سازمانی درست شد.',
          offerLow: 'باشه... اینو فعلاً به کسی تعریف نمی‌کنم.',
          offerMedium: 'خب، داریم به توافق نزدیک می‌شیم.',
          offerHigh:
            'از اول می‌دونستم اگه منطقی بیام جلو، شما هم منطقی رفتار می‌کنید.',
        },
        memory: {
          eggs: {
            no6a: 'شیش بار؟ مصاحبه‌مون خیلی جامع شده.',
            no6b: 'شیش تا رد شدم و هنوز مؤدبم. اینم یه مهارته.',
            no10a: 'ده بار؟ الان من کاندیدام یا کارمند قدیمی؟',
            no10b: 'ده تا شد. این پروسه رو بذارم تو رزومه‌م؟',
            leadHigh: 'خب، حالا وقتشه من یکی رو استخدام کنم.',
            leadLow: 'Team Lead با این پیشنهاد؟ اعتمادبه‌نفستون رو دوست داشتم.',
            persistenceYes: 'عه بالاخره! داشتم برای مرحله بعد آماده می‌شدم.',
            persistenceHigh: 'بعد این همه نه، این پیشنهاد؟ من شکایتی ندارم.',
          },
        },
      },

      date: {
        eyebrow: 'یه سؤال ساده',
        ask: {
          title: 'با من میای یه قهوه بخوریم؟',
          subtitle: 'فقط یه قهوه‌ست؛ اگه ساکت شدیم، می‌ندازیم گردن موزیک کافه.',
        },
        vibe: {
          eyebrow: 'خب، اصلش جور شد',
          title: 'کجا بریم؟',
          subtitle: 'استرسش با من؛ انتخابش با تو.',
          options: {
            cafe: {
              label: 'یه کافه دنج',
              detail: 'شروع راحت، جای کم‌سروصدا',
              icon: '☕',
            },
            dessert: {
              label: 'اول دسر',
              detail: 'تصمیم‌های عاقلانه برای فردا',
              icon: '🍰',
            },
            sunset: {
              label: 'بریم غروب ببینیم',
              detail: 'یه کم راه رفتن، یه منظره خوب',
              icon: '🌅',
            },
            movie: {
              label: 'فیلم و پاپ‌کورن',
              detail: 'سهم پاپ‌کورن قابل مذاکره‌ست',
              icon: '🎬',
            },
            surprise: {
              label: 'انتخاب با تو',
              detail: 'میام؛ غر هم نمی‌زنم',
              icon: '✨',
            },
          },
        },
        schedule: {
          eyebrow: 'ثبتش کنیم',
          title: 'کِی وقت داری؟',
          subtitle: 'یه ساعت انتخاب کن؛ منم فرصت داشته باشم سه بار لباسم رو عوض کنم.',
          dateLabel: 'یه روز انتخاب کن',
          timeLabel: 'یه ساعت انتخاب کن',
          chosen: '{{date}} ساعت {{time}}',
        },
        final: {
          seal: 'قرارمون قطعی شد',
          title: 'پس می‌بینمت',
          statement: 'قرار ثبت شد. کنسل‌کردن شامل جریمه‌ی دسر می‌شود.',
          activityLabel: 'برنامه',
          dateLabel: 'روز',
          timeLabel: 'ساعت',
          ticketNote: 'نگهش دار؛ برای بحثِ «ساعت چند بود؟» مدرک داریم.',
          speech: 'رسمی شد. حالا می‌تونم با خیال راحت ذوق کنم.',
          speech2: 'خب، این قسمت از برنامه دقیقاً طبق نقشه پیش رفت.',
          punchline1: 'قرار ثبت شد. کنسل‌کردن شامل جریمه‌ی دسر می‌شود.',
          punchline2: 'پرونده بسته شد. برم ببینم چی بپوشم.',
          punchline3: 'قرار قطعی شد. من از الان پنج دقیقه زودتر رسیدم.',
        },
        recipient: {
          label: 'اون',
          no1: 'این هفته خیلی سرم شلوغه.',
          no2: 'قهوه نمی‌خورم.',
          no3: 'بذار فکر کنم.',
          no4: 'شاید هفته بعد.',
          no5: 'نمی‌دونم کجا بریم.',
          no6: 'نمی‌دونم کجا بریم.',
          no7: 'ممکنه یکم دیر برسم.',
          no8: 'هنوز مطمئن نیستم.',
          no9: 'این روزا یکم خسته‌ام.',
          no10: 'شب‌ها ترجیح می‌دم خونه باشم.',
          no11: 'یکم یهوییه.',
        },
        reactions: {
          no1: 'من کوچولوم، جا می‌شم 🥺',
          no2: 'خب پس فلافل تصویب شد 😌',
          no3: 'فکر کن، من فعلاً وانمود می‌کنم استرس ندارم.',
          no4: 'باشه، من هفته بعدم برنامه‌م با توئه.',
          no5: 'تو فقط بیا، من یه جایی بلد می‌شم.',
          no6: 'این قسمت رو بسپر به من.',
          no7: 'پنج دقیقه‌تو از الان بخشیدم 😌',
          no8: 'من به اندازه‌ی هردومون مطمئنم 😌',
          no9: 'پس یه قرار آروم. منم قول می‌دم زیادی هیجان‌زده نشم... قول قطعی نیست.',
          no10: 'پس زودتر. ببین چقدر منطقی دارم مذاکره می‌کنم.',
          no11: 'برای تو شاید. من یه مدت بود برنامه داشتم 😌',
          noPool1: 'عه... این جواب توی برنامه‌م نبود.',
          noPool2: 'باشه حالا، یه کم ناز کن.',
          noPool3: 'اوکی... من فعلاً ناراحت نشدم. فعلاً.',
          noPool4: 'بازم نه؟ داری منو امتحان می‌کنی؟',
          noPool5: 'باشه، من هنوز شخصیت خودمو حفظ کردم.',
          yes: 'خب، الان باید وانمود کنم خیلی خونسردم.',
          cafe: 'کافه؟ خب، شروع امن و دوست‌داشتنی.',
          dessert: 'دسر انتخاب کردی؟ خب سلیقه‌ت تأیید شد.',
          sunset: 'غروب خوبه. یکم زیادی خوبه حتی.',
          movie: 'فیلم؟ خوبه، بعدش وقت داریم درباره‌ش الکی بحث کنیم.',
          surprise1: 'سورپرایز؟ خب حالا دیگه آبروی من وسطه.',
          surprise2: 'باشه. خودت خواستی، بعداً نگو زیادی خوب بود.',
          scheduled: 'گرفتم؛ سه تا یادآور می‌ذارم.',
          timeEarly: 'صبح زود؟ من اون ساعت هنوز شخصیت ندارم.',
          timeNoon: 'من ظهرا مثل بقیه تایما بانمک و جذابم 😌',
          timeAfternoon: 'من عصرا مثل بقیه تایما بانمک و جذابم 😌',
          timeNight: 'شب رو دوست دارم، رمانتیکه 😌',
          timeMidnight: 'نیمه‌شب؟ تو ظاهراً اهل تصمیم‌های معمولی نیستی.',
        },
        memory: {
          eggs: {
            no6a: 'شیش بار؟ باشه، یه ذره دارم به سرسختیت علاقه‌مند می‌شم.',
            no6b: 'شیش تا شد. این همه تلاش برای نه گفتن خودش یه جور توجهه 😌',
            no10a: 'ده بار؟ خب این رابطه حداقل از نظر آماری جدیه.',
            no10b: 'ده تا شد. من دیگه از اینجا به بعد فقط برای کنجکاوی موندم.',
            persistenceYes1: 'عه بالاخره! صبر کن، آمادگی این لحظه رو نداشتم.',
            persistenceYes2: 'دیدی؟ تهش آدمای منطقی همدیگه رو پیدا می‌کنن 😌',
            surpriseMidnight1: 'نیمه‌شب و سورپرایز؟ اعتماد به نفست قابل احترامه.',
            surpriseMidnight2: 'این ترکیب رو خودت انتخاب کردی‌ها. بعداً شاهد دارم.',
            manyActivities1: 'داری قرار انتخاب می‌کنی یا منو تست می‌کنی؟',
            manyActivities2: 'چهارمین انتخابه... من دارم با همه‌شون کنار میام.',
          },
        },
      },
    },
  },
} as const;
