export const resources = {
  en: {
    translation: {
      shared: {
        brand: 'tiny yes',
        scenario: 'Pick your mission',
        language: 'Language',
        kitten: 'Kitten',
        mascotLabel: 'Orange kitten mascot',
        decorations: {
          paycheck: 'PAY',
          resume: 'CV',
          hired: 'HIRED',
        },
        yes: 'Yes, deal 😌',
        no: 'Not yet',
        continue: 'That’s the one',
        answerHint: 'Your answer is down here',
        step: 'Step {{current}} of 4',
        scenarios: {
          raise: 'Ask for a raise',
          hire: 'Get me hired',
          date: 'Plan a date',
        },
      },

      raise: {
        eyebrow: 'Quick question, boss',
        ask: {
          title: 'Can we make my next paycheck a little better?',
          subtitle:
            'Nothing dramatic. Just enough to look at grocery prices without taking it personally.',
        },
        amount: {
          eyebrow: 'Let’s talk numbers',
          title: 'How good is this news?',
          subtitle: 'Choose freely. I have prepared several facial expressions.',
          options: {
            five: { label: '5%', detail: 'A cautious beginning' },
            ten: { label: '10%', detail: 'Now we’re talking' },
            twenty: { label: '20%', detail: 'That would actually help' },
            thirty: { label: '30%', detail: 'Now that’s a number' },
          },
        },
        timing: {
          eyebrow: 'One last detail',
          title: 'When does payroll find out?',
          subtitle: '“Soon” is not technically a date. I checked.',
          options: {
            next: { label: 'Next paycheck', detail: 'Excellent management' },
            month: { label: 'This month', detail: 'I can work with that' },
            meeting: { label: 'After a meeting', detail: 'Fine. No 47-slide deck.' },
            surprise: { label: 'Surprise me', detail: 'Bold. I respect it.' },
          },
        },
        final: {
          seal: 'PAYROLL HAS BEEN INFORMED',
          title: 'Approved. I have witnesses.',
          statement: 'I’ll bring this exact energy to the next meeting.',
          selectedLabel: 'You picked',
          adjustmentLabel: 'Added after review',
          amountLabel: 'Approved raise',
          timingLabel: 'Effective',
          mischief: 'Two points were added for time spent attending meetings.',
          speech: 'I’ll act surprised on payday.',
        },
        recipient: {
          label: 'Boss',
          no1: 'Can we revisit this next month?',
          no2: 'The budget is tight.',
          no3: 'Finance said no.',
          no4: 'Let’s schedule a meeting.',
          no5: 'I need to think about it.',
          noLate: 'Let’s circle back later.',
        },
        reactions: {
          no1: 'We’re revisiting it right now.',
          no2: 'Give it a little stretch.',
          no3: 'Finance says a lot of things. 😐',
          no4: 'This meeting already has an answer.',
          no5: 'I did the thinking for both of us. It’s a yes.',
          noLate: 'We have circled. Raise, please.',
          yes: 'That was the correct button.',
          amount5: 'We can recover from this.',
          amount10: 'A respectable opening.',
          amount20: 'Now I feel seen.',
          amount30: 'I’ll clear my afternoon.',
          timing: 'Good. I’m counting from then.',
        },
      },

      hire: {
        eyebrow: 'A very short application',
        ask: {
          title: 'Should I just join your team?',
          subtitle: 'We can skip the mysterious “we’ll be in touch” part.',
        },
        role: {
          eyebrow: 'Let’s print the badge',
          title: 'What goes under my name?',
          subtitle: 'Pick carefully. I will update my bio immediately.',
          options: {
            member: {
              label: 'Team Member',
              detail: 'Reliable. Knows where the snacks are.',
            },
            specialist: {
              label: 'Specialist',
              detail: 'Gets called when it gets weird',
            },
            lead: { label: 'Team Lead', detail: 'Owns a notebook and opinions' },
          },
        },
        offer: {
          eyebrow: 'Now the serious part',
          title: 'How quickly am I saying yes?',
          subtitle: 'No salary fields here. We’re keeping this friendship alive.',
          options: {
            cute: { label: 'Let me think', detail: 'A polite opening. Very polite.' },
            talk: { label: 'Send the paperwork', detail: 'Now we have a conversation.' },
            sign: { label: 'Where’s the pen?', detail: 'I forgot every other interview.' },
          },
        },
        final: {
          seal: 'ACCESS GRANTED',
          title: 'Hired. Excellent decision.',
          statement: 'I’ll learn everyone’s name by the second coffee.',
          passLabel: 'NEW TEAM MEMBER',
          roleLabel: 'Position',
          offerLabel: 'Offer status',
          upgrade: 'Cleared for the first day',
          speech: 'Great. Where do you keep the coffee?',
        },
        recipient: {
          label: 'Recruiter',
          no1: 'We’re still reviewing applications.',
          no2: 'There may be another interview.',
          no3: 'We need someone with more experience.',
          no4: 'The role is on hold.',
          no5: 'We’ll keep your résumé on file.',
          noLate: 'We’ll be in touch.',
        },
        reactions: {
          no1: 'Great. Stop when you reach mine.',
          no2: 'I was saving my best nod for it.',
          no3: 'Let me get that experience here.',
          no4: 'Take it off hold for five minutes. I’ll be quick.',
          no5: 'My résumé would prefer a desk.',
          noLate: 'I am famously reachable. Right now works.',
          yes: 'I’ll pretend to be surprised.',
          member: 'Good. I already found the group chat.',
          specialist: 'Correct. I do have a serious face.',
          lead: 'First decision: fewer meetings.',
          offerCute: 'That sounded like “negotiable.”',
          offerTalk: 'Good. Keep that page open.',
          offerSign: 'I brought my own pen.',
        },
      },

      date: {
        eyebrow: 'A low-pressure question',
        ask: {
          title: 'Want to get coffee with me?',
          subtitle: 'One coffee. If it’s awkward, we can blame the chairs.',
        },
        vibe: {
          eyebrow: 'Okay, we have a plan',
          title: 'What sounds good?',
          subtitle: 'I’ll handle the nerves. You pick the place.',
          options: {
            cafe: {
              label: 'Coffee somewhere cozy',
              detail: 'Easy start. Good lighting.',
              icon: '☕',
            },
            dessert: {
              label: 'Dessert first',
              detail: 'Responsible choices can wait.',
              icon: '🍰',
            },
            sunset: {
              label: 'Catch the sunset',
              detail: 'A walk and something nice to look at',
              icon: '🌅',
            },
            movie: {
              label: 'Movie night',
              detail: 'Shared popcorn. Terms negotiable.',
              icon: '🎬',
            },
            surprise: {
              label: 'Choose for me',
              detail: 'I’ll show up with no complaints.',
              icon: '✨',
            },
          },
        },
        schedule: {
          eyebrow: 'Put it in the calendar',
          title: 'When are you free?',
          subtitle: 'Pick a time. I need a fair chance to decide what to wear.',
          dateLabel: 'Pick a day',
          timeLabel: 'Pick a time',
          chosen: '{{date}} at {{time}}',
        },
        final: {
          seal: 'IT’S A DATE',
          title: 'See you there.',
          statement: 'I’ll be on time, give or take one outfit change.',
          activityLabel: 'The plan',
          dateLabel: 'Day',
          timeLabel: 'Time',
          ticketNote: 'Keep this. It settles any future “what time was it?” debate.',
          speech: 'Cool. I’ll try not to arrive twenty minutes early.',
        },
        recipient: {
          label: 'Them',
          no1: 'This week is packed.',
          no2: 'I don’t drink coffee.',
          no3: 'Let me think about it.',
          no4: 'I never know where to go.',
          no5: 'I might be awkward.',
          noLate: 'Let me check my calendar.',
        },
        reactions: {
          no1: 'I only need one free hour. I’ll bring coffee.',
          no2: 'Cafés have tea. This is going fine.',
          no3: 'Sure. I’ll wait over here casually.',
          no4: 'Excellent. I brought options.',
          no5: 'Great. We can take turns.',
          noLate: 'Take your time. I’m practicing patience.',
          yes: 'Okay. Nobody panic.',
          cafe: 'Good. I know a table.',
          dessert: 'I respect this decision.',
          sunset: 'I’ll check the weather seventeen times.',
          movie: 'I’ll share the popcorn. Probably.',
          surprise: 'Alright. I’ll be brave about it.',
          scheduled: 'Got it. I’m setting three reminders.',
        },
      },
    },
  },

  fa: {
    translation: {
      shared: {
        brand: 'یه آره کوچولو',
        scenario: 'امروز کدوم مأموریت؟',
        language: 'زبان',
        kitten: 'گربه',
        mascotLabel: 'گربه نارنجی',
        decorations: {
          paycheck: 'فیش',
          resume: 'رزومه',
          hired: 'استخدام',
        },
        yes: 'آره، قبوله 😌',
        no: 'فعلاً نه',
        continue: 'همینه، قطعی‌ش کن',
        answerHint: 'جوابت همین پایینه',
        step: 'مرحله {{current}} از ۴',
        scenarios: {
          raise: 'افزایش حقوق',
          hire: 'منو استخدام کن',
          date: 'قرار دونفره',
        },
      },

      raise: {
        eyebrow: 'رئیس، یه دقیقه کار دارم',
        ask: {
          title: 'می‌شه فیش بعدیم یه کم بهتر باشه؟',
          subtitle:
            'چیز عجیبی نمی‌خوام؛ فقط آخر ماه، قبل از هر خرید، لازم نباشه با خودم جلسه بذارم.',
        },
        amount: {
          eyebrow: 'بریم سراغ عددها',
          title: 'این خبر خوب، چقدر خوبه؟',
          subtitle: 'راحت انتخاب کن؛ من برای هر گزینه یه قیافه آماده دارم.',
          options: {
            five: { label: '۵٪', detail: 'شروع محتاطانه' },
            ten: { label: '۱۰٪', detail: 'خب، شد یه چیزی' },
            twenty: { label: '۲۰٪', detail: 'این یکی آبرومنده' },
            thirty: { label: '۳۰٪', detail: 'می‌دونستم دستت بازه' },
          },
        },
        timing: {
          eyebrow: 'فقط تاریخ اجرا',
          title: 'مالی از کی باید در جریان باشه؟',
          subtitle: '«به‌زودی» تاریخ حساب نمی‌شه؛ پرسیدم.',
          options: {
            next: { label: 'از فیش بعدی', detail: 'مدیریت یعنی همین' },
            month: { label: 'همین ماه', detail: 'قبوله، منطقیه' },
            meeting: { label: 'بعد از یه جلسه', detail: 'باشه؛ فقط ۴۷ تا اسلاید نه' },
            surprise: { label: 'سورپرایزم کن', detail: 'ریسکیه؛ خوشم اومد' },
          },
        },
        final: {
          seal: 'مالی در جریان قرار گرفت',
          title: 'تصویب شد؛ شاهد هم دارم',
          statement: 'از این به بعد با انگیزه بیشتری وانمود می‌کنم جلسه‌ها کوتاهن.',
          selectedLabel: 'انتخاب شما',
          adjustmentLabel: 'بعد از بررسی',
          amountLabel: 'افزایش تصویب‌شده',
          timingLabel: 'زمان اجرا',
          mischief: 'دو درصد هم بابت رفت‌وآمد تا جلسه‌ها اضافه شد.',
          speech: 'وقتی فیش اومد خیلی عادی رفتار می‌کنم.',
        },
        recipient: {
          label: 'مدیر',
          no1: 'بذار ماه بعد دوباره ببینیم.',
          no2: 'بودجه یه کم بسته‌ست.',
          no3: 'مالی گفته فعلاً نه.',
          no4: 'بذار یه جلسه براش بذاریم.',
          no5: 'باید بیشتر فکر کنم.',
          noLate: 'بذار بعداً برگردیم سرش.',
        },
        reactions: {
          no1: 'همین الان داریم دوباره می‌بینیمش.',
          no2: 'یه کم بازش کنین.',
          no3: 'مالی خیلی حرف می‌زنه 😐',
          no4: 'جواب جلسه که معلومه.',
          no5: 'من فکرهاشو کردم؛ جواب آره‌ست.',
          noLate: 'برگشتیم. افزایش حقوق، لطفاً.',
          yes: 'دکمه درست همین بود.',
          amount5: 'قابل جبرانه.',
          amount10: 'برای شروع بد نیست.',
          amount20: 'خب، این شد حرف حساب.',
          amount30: 'بعدازظهرم رو برای جشن خالی می‌کنم.',
          timing: 'خب، از همون موقع حساب می‌کنم.',
        },
      },

      hire: {
        eyebrow: 'یه درخواست کاری کوتاه',
        ask: {
          title: 'چطوره منو بیارین تو تیمتون؟',
          subtitle: 'اون بخشِ «خبرتون می‌کنیم» رو هم می‌تونیم رد کنیم.',
        },
        role: {
          eyebrow: 'بریم کارت پرسنلی رو چاپ کنیم',
          title: 'زیر اسمم چی بنویسیم؟',
          subtitle: 'دقیق انتخاب کنین؛ من همون لحظه عنوان شغلیم رو عوض می‌کنم.',
          options: {
            member: {
              label: 'عضو تیم',
              detail: 'قابل اعتماد؛ جای خوراکی‌ها رو هم بلده',
            },
            specialist: {
              label: 'متخصص',
              detail: 'وقتی کار گره می‌خوره صدام می‌کنن',
            },
            lead: { label: 'رهبر تیم', detail: 'دفترچه داره، نظر هم زیاد داره' },
          },
        },
        offer: {
          eyebrow: 'حالا بخش جدی ماجرا',
          title: 'چقدر سریع بگم قبوله؟',
          subtitle: 'عدد نمی‌پرسیم؛ دوستیمون رو برای بعد از قرارداد لازم داریم.',
          options: {
            cute: { label: 'بذار فکر کنم', detail: 'شروع مؤدبانه‌ایه؛ خیلی مؤدبانه' },
            talk: { label: 'قرارداد رو بفرستین', detail: 'خب، حالا داریم حرف می‌زنیم' },
            sign: { label: 'خودکار کجاست؟', detail: 'مصاحبه‌های دیگه یادم رفت' },
          },
        },
        final: {
          seal: 'دسترسی صادر شد',
          title: 'استخدام شدم؛ تصمیم خوبیه',
          statement: 'اسم همه رو تا قهوه دوم یاد می‌گیرم.',
          passLabel: 'عضو جدید تیم',
          roleLabel: 'سمت',
          offerLabel: 'وضعیت پیشنهاد',
          upgrade: 'آماده برای اولین روز کاری',
          speech: 'عالیه. دستگاه قهوه کجاست؟',
        },
        recipient: {
          label: 'کارشناس جذب',
          no1: 'هنوز داریم رزومه‌ها رو بررسی می‌کنیم.',
          no2: 'شاید یه مصاحبه دیگه هم لازم باشه.',
          no3: 'یه کم سابقه بیشتر می‌خوایم.',
          no4: 'فعلاً موقعیت رو نگه داشتیم.',
          no5: 'رزومه‌ت رو نگه می‌داریم.',
          noLate: 'خبرت می‌کنیم.',
        },
        reactions: {
          no1: 'عالیه؛ به مال من که رسیدین نگه دارین.',
          no2: 'باشه؛ سر تکون‌دادن حرفه‌ایم رو نگه داشته بودم.',
          no3: 'سابقه رو از کجا بیارم؟ از همین‌جا شروع کنیم.',
          no4: 'پنج دقیقه بازش کنین؛ سریع استخدام می‌شم.',
          no5: 'رزومه‌م میز رو ترجیح می‌ده.',
          noLate: 'من خیلی راحت خبر می‌شم؛ همین الان هم می‌شه.',
          yes: 'منم وانمود می‌کنم غافلگیر شدم.',
          member: 'خوبه؛ گروه کاری رو هم پیدا کردم.',
          specialist: 'درسته؛ قیافه جدی هم دارم.',
          lead: 'اولین تصمیم: جلسه کمتر.',
          offerCute: 'من «قابل مذاکره» شنیدم.',
          offerTalk: 'خوبه؛ همین صفحه رو باز نگه دارین.',
          offerSign: 'خودکار خودمم آوردم.',
        },
      },

      date: {
        eyebrow: 'یه سؤال ساده',
        ask: {
          title: 'با من میای یه قهوه بخوریم؟',
          subtitle: 'فقط یه قهوه‌ست؛ اگه ساکت شدیم، می‌ندازیم گردن موزیک کافه.',
        },
        vibe: {
          eyebrow: 'خب، اصلش جور شد',
          title: 'کجا بریم؟',
          subtitle: 'استرسش با من؛ انتخابش با تو.',
          options: {
            cafe: {
              label: 'یه کافه دنج',
              detail: 'شروع راحت، جای کم‌سروصدا',
              icon: '☕',
            },
            dessert: {
              label: 'اول دسر',
              detail: 'تصمیم‌های عاقلانه برای فردا',
              icon: '🍰',
            },
            sunset: {
              label: 'بریم غروب ببینیم',
              detail: 'یه کم راه رفتن، یه منظره خوب',
              icon: '🌅',
            },
            movie: {
              label: 'فیلم و پاپ‌کورن',
              detail: 'سهم پاپ‌کورن قابل مذاکره‌ست',
              icon: '🎬',
            },
            surprise: {
              label: 'انتخاب با تو',
              detail: 'میام؛ غر هم نمی‌زنم',
              icon: '✨',
            },
          },
        },
        schedule: {
          eyebrow: 'ثبتش کنیم',
          title: 'کِی وقت داری؟',
          subtitle: 'یه ساعت انتخاب کن؛ منم فرصت داشته باشم سه بار لباسم رو عوض کنم.',
          dateLabel: 'یه روز انتخاب کن',
          timeLabel: 'یه ساعت انتخاب کن',
          chosen: '{{date}} ساعت {{time}}',
        },
        final: {
          seal: 'قرارمون قطعی شد',
          title: 'پس می‌بینمت',
          statement: 'سر وقت می‌رسم؛ مگر این‌که دوباره لباسم رو عوض کنم.',
          activityLabel: 'برنامه',
          dateLabel: 'روز',
          timeLabel: 'ساعت',
          ticketNote: 'نگهش دار؛ برای بحثِ «ساعت چند بود؟» مدرک داریم.',
          speech: 'خوبه. سعی می‌کنم بیست دقیقه زودتر نرسم.',
        },
        recipient: {
          label: 'اون',
          no1: 'این هفته خیلی سرم شلوغه.',
          no2: 'من قهوه نمی‌خورم.',
          no3: 'بذار یکم فکر کنم.',
          no4: 'نمی‌دونم کجا بریم.',
          no5: 'من شاید یکم معذب باشم.',
          noLate: 'بذار تقویمم رو ببینم.',
        },
        reactions: {
          no1: 'یه ساعت خالی کافیه؛ قهوه با من.',
          no2: 'کافه چای هم داره؛ هنوز همه‌چی مرتبه.',
          no3: 'باشه؛ من این‌جا خیلی عادی منتظرم.',
          no4: 'عالیه؛ من گزینه آوردم.',
          no5: 'خوبه؛ نوبتی معذب می‌شیم.',
          noLate: 'راحت باش؛ من دارم صبرکردن تمرین می‌کنم.',
          yes: 'باشه. من خیلی خونسردم.',
          cafe: 'خوبه؛ یه میز خوب سراغ دارم.',
          dessert: 'این تصمیم کاملاً محترمه.',
          sunset: 'هوا رو فقط هفده بار چک می‌کنم.',
          movie: 'پاپ‌کورن رو تقسیم می‌کنم. احتمالاً.',
          surprise: 'باشه؛ به انتخابت اعتماد می‌کنم.',
          scheduled: 'گرفتم؛ سه تا یادآور می‌ذارم.',
        },
      },
    },
  },
} as const;
